/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ApplicationInput = IDL.Record({
  'jobId' : IDL.Nat,
  'coverLetter' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Job = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'salary' : IDL.Opt(IDL.Nat),
  'description' : IDL.Text,
  'company' : IDL.Text,
  'employer' : IDL.Principal,
  'requirements' : IDL.Vec(IDL.Text),
  'location' : IDL.Text,
});
export const EmployerProfile = IDL.Record({
  'description' : IDL.Text,
  'companyLogo' : IDL.Text,
  'companyName' : IDL.Text,
  'companyWebsite' : IDL.Text,
});
export const CandidateProfile = IDL.Record({
  'resume' : IDL.Text,
  'fullName' : IDL.Text,
  'skills' : IDL.Vec(IDL.Text),
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'linkedin' : IDL.Text,
  'role' : UserRole,
  'employer' : IDL.Opt(EmployerProfile),
  'candidate' : IDL.Opt(CandidateProfile),
  'github' : IDL.Text,
});
export const ApplicationStatus = IDL.Variant({
  'hired' : IDL.Null,
  'offer' : IDL.Null,
  'interview' : IDL.Null,
  'applied' : IDL.Null,
  'rejected' : IDL.Null,
  'withdrawn' : IDL.Null,
});
export const JobApplication = IDL.Record({
  'id' : IDL.Nat,
  'status' : ApplicationStatus,
  'jobId' : IDL.Nat,
  'coverLetter' : IDL.Text,
  'candidate' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'applyForJob' : IDL.Func([ApplicationInput], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'chooseRole' : IDL.Func([UserRole], [], []),
  'createJob' : IDL.Func([Job], [], []),
  'deleteJob' : IDL.Func([IDL.Nat], [], []),
  'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getApplications' : IDL.Func([], [IDL.Vec(JobApplication)], ['query']),
  'getApplicationsForCandidate' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(JobApplication)],
      ['query'],
    ),
  'getApplicationsForJob' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(JobApplication)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getJob' : IDL.Func([IDL.Nat], [Job], ['query']),
  'getJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
  'getJobsByEmployer' : IDL.Func([IDL.Principal], [IDL.Vec(Job)], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateApplicationStatus' : IDL.Func([IDL.Nat, ApplicationStatus], [], []),
  'updateUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ApplicationInput = IDL.Record({
    'jobId' : IDL.Nat,
    'coverLetter' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Job = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'salary' : IDL.Opt(IDL.Nat),
    'description' : IDL.Text,
    'company' : IDL.Text,
    'employer' : IDL.Principal,
    'requirements' : IDL.Vec(IDL.Text),
    'location' : IDL.Text,
  });
  const EmployerProfile = IDL.Record({
    'description' : IDL.Text,
    'companyLogo' : IDL.Text,
    'companyName' : IDL.Text,
    'companyWebsite' : IDL.Text,
  });
  const CandidateProfile = IDL.Record({
    'resume' : IDL.Text,
    'fullName' : IDL.Text,
    'skills' : IDL.Vec(IDL.Text),
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'linkedin' : IDL.Text,
    'role' : UserRole,
    'employer' : IDL.Opt(EmployerProfile),
    'candidate' : IDL.Opt(CandidateProfile),
    'github' : IDL.Text,
  });
  const ApplicationStatus = IDL.Variant({
    'hired' : IDL.Null,
    'offer' : IDL.Null,
    'interview' : IDL.Null,
    'applied' : IDL.Null,
    'rejected' : IDL.Null,
    'withdrawn' : IDL.Null,
  });
  const JobApplication = IDL.Record({
    'id' : IDL.Nat,
    'status' : ApplicationStatus,
    'jobId' : IDL.Nat,
    'coverLetter' : IDL.Text,
    'candidate' : IDL.Principal,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'applyForJob' : IDL.Func([ApplicationInput], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'chooseRole' : IDL.Func([UserRole], [], []),
    'createJob' : IDL.Func([Job], [], []),
    'deleteJob' : IDL.Func([IDL.Nat], [], []),
    'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getApplications' : IDL.Func([], [IDL.Vec(JobApplication)], ['query']),
    'getApplicationsForCandidate' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(JobApplication)],
        ['query'],
      ),
    'getApplicationsForJob' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(JobApplication)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getJob' : IDL.Func([IDL.Nat], [Job], ['query']),
    'getJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
    'getJobsByEmployer' : IDL.Func([IDL.Principal], [IDL.Vec(Job)], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateApplicationStatus' : IDL.Func([IDL.Nat, ApplicationStatus], [], []),
    'updateUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };