/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ApplicationInput { 'jobId' : bigint, 'coverLetter' : string }
export type ApplicationStatus = { 'hired' : null } |
  { 'offer' : null } |
  { 'interview' : null } |
  { 'applied' : null } |
  { 'rejected' : null } |
  { 'withdrawn' : null };
export interface CandidateProfile {
  'resume' : string,
  'fullName' : string,
  'skills' : Array<string>,
}
export interface EmployerProfile {
  'description' : string,
  'companyLogo' : string,
  'companyName' : string,
  'companyWebsite' : string,
}
export interface Job {
  'id' : bigint,
  'title' : string,
  'salary' : [] | [bigint],
  'description' : string,
  'company' : string,
  'employer' : Principal,
  'requirements' : Array<string>,
  'location' : string,
}
export interface JobApplication {
  'id' : bigint,
  'status' : ApplicationStatus,
  'jobId' : bigint,
  'coverLetter' : string,
  'candidate' : Principal,
}
export interface UserProfile {
  'bio' : string,
  'linkedin' : string,
  'role' : UserRole,
  'employer' : [] | [EmployerProfile],
  'candidate' : [] | [CandidateProfile],
  'github' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'applyForJob' : ActorMethod<[ApplicationInput], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'chooseRole' : ActorMethod<[UserRole], undefined>,
  'createJob' : ActorMethod<[Job], undefined>,
  'deleteJob' : ActorMethod<[bigint], undefined>,
  'getAllUserProfiles' : ActorMethod<[], Array<UserProfile>>,
  'getApplications' : ActorMethod<[], Array<JobApplication>>,
  'getApplicationsForCandidate' : ActorMethod<
    [Principal],
    Array<JobApplication>
  >,
  'getApplicationsForJob' : ActorMethod<[bigint], Array<JobApplication>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getJob' : ActorMethod<[bigint], Job>,
  'getJobs' : ActorMethod<[], Array<Job>>,
  'getJobsByEmployer' : ActorMethod<[Principal], Array<Job>>,
  'getUserProfile' : ActorMethod<[Principal], UserProfile>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateApplicationStatus' : ActorMethod<
    [bigint, ApplicationStatus],
    undefined
  >,
  'updateUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];