/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CandidateProfile {
  'resume' : string,
  'currentOrLastCompany' : string,
  'jobRole' : string,
  'totalExperience' : bigint,
  'lastDrawnSalary' : bigint,
  'fullName' : string,
  'mobileNumber' : MobileNumber,
  'isActive' : boolean,
  'email' : string,
  'preferredLocation' : string,
  'skills' : Array<string>,
}
export interface Employer {
  'principal' : Principal,
  'credits' : bigint,
  'creditsPurchased' : bigint,
}
export interface EmployerProfile {
  'description' : string,
  'mobileNumber' : MobileNumber,
  'businessLocation' : string,
  'email' : string,
  'companyLogo' : string,
  'companyName' : string,
  'companyWebsite' : string,
  'contactPersonName' : string,
}
export type MobileNumber = string;
export interface UnlockRecord {
  'employer' : Principal,
  'timestamp' : bigint,
  'candidate' : Principal,
  'creditsUsed' : bigint,
  'profileDetails' : CandidateProfile,
}
export interface UnlockResult {
  'status' : string,
  'currentCredits' : bigint,
  'remainingCredits' : bigint,
}
export interface UserProfile {
  'bio' : string,
  'linkedin' : string,
  'employer' : [] | [EmployerProfile],
  'candidate' : [] | [CandidateProfile],
  'github' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCredits' : ActorMethod<[Principal, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deductCredits' : ActorMethod<[Principal, bigint], undefined>,
  'getAllEmployers' : ActorMethod<[], Array<Employer>>,
  'getAllJobseekers' : ActorMethod<[], Array<Principal>>,
  'getAllUnlockLogs' : ActorMethod<[], Array<[Principal, Array<UnlockRecord>]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCandidateDirectory' : ActorMethod<[], Array<UserProfile>>,
  'getCreditBalance' : ActorMethod<[], bigint>,
  'getCreditCostPerUnlock' : ActorMethod<[], bigint>,
  'getCurrentUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getEmployerCredits' : ActorMethod<[Principal], [] | [Employer]>,
  'getProfile' : ActorMethod<[Principal], UserProfile>,
  'getSessionTimeout' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setCreditCostPerUnlock' : ActorMethod<[bigint], undefined>,
  'setSessionTimeout' : ActorMethod<[bigint], undefined>,
  'unlockCandidateProfile' : ActorMethod<[Principal], UnlockResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];