/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Employer = IDL.Record({
  'principal' : IDL.Principal,
  'credits' : IDL.Nat,
  'creditsPurchased' : IDL.Nat,
});
export const MobileNumber = IDL.Text;
export const CandidateProfile = IDL.Record({
  'resume' : IDL.Text,
  'currentOrLastCompany' : IDL.Text,
  'jobRole' : IDL.Text,
  'totalExperience' : IDL.Nat,
  'lastDrawnSalary' : IDL.Nat,
  'fullName' : IDL.Text,
  'mobileNumber' : MobileNumber,
  'isActive' : IDL.Bool,
  'email' : IDL.Text,
  'preferredLocation' : IDL.Text,
  'skills' : IDL.Vec(IDL.Text),
});
export const UnlockRecord = IDL.Record({
  'employer' : IDL.Principal,
  'timestamp' : IDL.Int,
  'candidate' : IDL.Principal,
  'creditsUsed' : IDL.Nat,
  'profileDetails' : CandidateProfile,
});
export const EmployerProfile = IDL.Record({
  'description' : IDL.Text,
  'mobileNumber' : MobileNumber,
  'businessLocation' : IDL.Text,
  'email' : IDL.Text,
  'companyLogo' : IDL.Text,
  'companyName' : IDL.Text,
  'companyWebsite' : IDL.Text,
  'contactPersonName' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'linkedin' : IDL.Text,
  'employer' : IDL.Opt(EmployerProfile),
  'candidate' : IDL.Opt(CandidateProfile),
  'github' : IDL.Text,
});
export const UnlockResult = IDL.Record({
  'status' : IDL.Text,
  'currentCredits' : IDL.Nat,
  'remainingCredits' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCredits' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deductCredits' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'getAllEmployers' : IDL.Func([], [IDL.Vec(Employer)], ['query']),
  'getAllJobseekers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getAllUnlockLogs' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(UnlockRecord)))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCandidateDirectory' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getCreditBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'getCreditCostPerUnlock' : IDL.Func([], [IDL.Nat], ['query']),
  'getCurrentUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getEmployerCredits' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(Employer)],
      ['query'],
    ),
  'getProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
  'getSessionTimeout' : IDL.Func([], [IDL.Int], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setCreditCostPerUnlock' : IDL.Func([IDL.Nat], [], []),
  'setSessionTimeout' : IDL.Func([IDL.Int], [], []),
  'unlockCandidateProfile' : IDL.Func([IDL.Principal], [UnlockResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Employer = IDL.Record({
    'principal' : IDL.Principal,
    'credits' : IDL.Nat,
    'creditsPurchased' : IDL.Nat,
  });
  const MobileNumber = IDL.Text;
  const CandidateProfile = IDL.Record({
    'resume' : IDL.Text,
    'currentOrLastCompany' : IDL.Text,
    'jobRole' : IDL.Text,
    'totalExperience' : IDL.Nat,
    'lastDrawnSalary' : IDL.Nat,
    'fullName' : IDL.Text,
    'mobileNumber' : MobileNumber,
    'isActive' : IDL.Bool,
    'email' : IDL.Text,
    'preferredLocation' : IDL.Text,
    'skills' : IDL.Vec(IDL.Text),
  });
  const UnlockRecord = IDL.Record({
    'employer' : IDL.Principal,
    'timestamp' : IDL.Int,
    'candidate' : IDL.Principal,
    'creditsUsed' : IDL.Nat,
    'profileDetails' : CandidateProfile,
  });
  const EmployerProfile = IDL.Record({
    'description' : IDL.Text,
    'mobileNumber' : MobileNumber,
    'businessLocation' : IDL.Text,
    'email' : IDL.Text,
    'companyLogo' : IDL.Text,
    'companyName' : IDL.Text,
    'companyWebsite' : IDL.Text,
    'contactPersonName' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'linkedin' : IDL.Text,
    'employer' : IDL.Opt(EmployerProfile),
    'candidate' : IDL.Opt(CandidateProfile),
    'github' : IDL.Text,
  });
  const UnlockResult = IDL.Record({
    'status' : IDL.Text,
    'currentCredits' : IDL.Nat,
    'remainingCredits' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCredits' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deductCredits' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'getAllEmployers' : IDL.Func([], [IDL.Vec(Employer)], ['query']),
    'getAllJobseekers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getAllUnlockLogs' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(UnlockRecord)))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCandidateDirectory' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getCreditBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getCreditCostPerUnlock' : IDL.Func([], [IDL.Nat], ['query']),
    'getCurrentUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getEmployerCredits' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(Employer)],
        ['query'],
      ),
    'getProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
    'getSessionTimeout' : IDL.Func([], [IDL.Int], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setCreditCostPerUnlock' : IDL.Func([IDL.Nat], [], []),
    'setSessionTimeout' : IDL.Func([IDL.Int], [], []),
    'unlockCandidateProfile' : IDL.Func([IDL.Principal], [UnlockResult], []),
  });
};

export const init = ({ IDL }) => { return []; };